# Generated by Django 5.1.6 on 2025-04-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
